config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :todos, only: [ :index, :create, :destroy, :update ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get "profile", to: "profile#index", as: :profile
  root "todos#index"

  get "*path", to: redirect("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  after_create_commit -> { broadcast_append_to "todos", target: "todos-list" }
  after_update_commit -> { broadcast_replace_to "todos" }
  after_destroy_commit -> { broadcast_remove_to "todos" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
   before_action :set_todo, only: [ :update, :destroy ]

  def index
    @todos = Todo.all.order(created_at: :desc)
  end



  def create
   @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}_form", partial: "form", locals: { todo: @todo }) }
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}", partial: "todo", locals: { todo: @todo }) }
        format.html { redirect_to root_path, notice: "Todo updated successfully." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
   @todo.destroy!
   @todos = Todo.all.order(created_at: :desc)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: "Todo was successfully destroyed." }
    end
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My Academy Todoapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="bg-[#353734]">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="bg-[#C0C6BC] p-6 rounded-xl shadow-md w-full max-w-2xl">
  <%= form_with(model: [todo],
              data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }, 
              class: "w-full flex flex-col gap-4") do |form| %>
    <% if todo.errors.any? %>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-md">
        <h2 class="font-bold"><%= pluralize(todo.errors.count, "error") %> prevented this todo from being saved:</h2>
        <ul class="list-disc list-inside">
          <% todo.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="flex items-center gap-4">
      <%= form.text_field :title, 
          placeholder: "Enter a task...",
          data: { testid: "input-feild" } ,
          class: " flex-1 rounded-lg  bg-white px-3 py-2 text-[#353734] placeholder-[#514F4D]/60 shadow-sm focus:outline-none focus:ring-2 focus:ring-[#DDBD9C]" %>
      <%= form.button "Add", 
          type: :submit, 
          name: "todo[status]", 
          value: false, 
          data: { testid: "add-btn" } ,
          class: "max-md:hidden px-4 py-2 bg-[#3D4140] text-white rounded-lg hover:bg-[#FFA300] transition shadow-md" %>
      <%= form.button type: :submit, 
                name: "todo[status]", 
                value: false,
                data: { testid: "add-btn" } , 
                class: "min-md:hidden px-2 py-2 bg-[#FFA500] text-white rounded-lg hover:bg-[#FFA300] transition shadow-md flex items-center gap-2" do %>
        <%= image_tag "plus-svgrepo-com.svg", class: "max-w-6 max-h-6"%>
      <% end %>
    </div>
  <% end %>
</div>

app/views/todos/_todo.html.erb
<li id="<%= dom_id(todo) %>" data-testid="todo-id-<%= todo.id %>-item" 
    class="todo-item bg-[#C0C6BC] transition rounded-xl shadow-md p-4">
  <div class="flex items-center justify-between">
    <div class="flex items-center min-md:gap-4 max-md:gap-2">
      <span class="todo-status ml-2 flex-1">
        <% if todo.completed %>
          <%= button_to todo_path(todo, todo: { completed: false }), 
              method: :patch, 
              data: {  testid: "todo-id-#{ todo.id }-check-checkbox" }, 
              class: "w-8 h-8 flex justify-center cursor-pointer" do %>
            <%= image_tag "checkbox-check-svgrepo-com.svg", class: "w-8 h-8"%>
          <% end %>
        <% else %>
          <%= button_to todo_path(todo, todo: { completed: true }), 
              method: :patch, 
              data: { testid: "todo-id-#{ todo.id }-uncheck-checkbox" }, 
              class: "w-8 h-8 flex justify-center cursor-pointer" do %>
            <%= image_tag "checkbox-svgrepo-com.svg", class: "w-8 h-8" %>
          <% end %>
        <% end %>
      </span>
      <span class="todo-title <%= 'line-through text-[#514F4D] opacity-70' if todo.completed %> flex-none text-lg max-lg:text-md max-md:text-sm max-sm:text-[12px] font-semibold text-[#3D4140] mx-2 truncate max-w-[400px] max-lg:max-w-[20vw] max-md:max-w-[40vw] @max-[320px]:max-w-[10vw] block"
      data-testid="todo-title-id-<%= todo.id %>" >
        <%= todo.title %>
      </span>
    </div>
    <div class="todo-actions ml-2">
      <%= button_to  todo_path(todo),
            method: :delete, 
            data: { testid: "todo-id-#{ todo.id }-del-btn" }, 
            class: "px-2 py-2 rounded-lg bg-red-500 text-white hover:bg-red-600 transition max-md:text-sm" do %>
        <%= image_tag "xmark-svgrepo-com.svg", class: "w-4 h-4" %>
      <% end %>
    </div>
  </div>
</li>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos-list", partial: "todos/todo", locals: { todo: @todo } %>
<%= turbo_stream.replace "new_todo", partial: "form", locals: { todo: Todo.new } %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@todo) %>

app/views/todos/edit.html.erb
<turbo-frame id="new_todo">
  <%= render "form", todo: @todo %>
<turbo-frame>

app/views/todos/index.html.erb
<div class="w-full h-full min-h-screen bg-[#353734]">
  <div class="flex flex-col min-lg:mx-40 bg-[#DDBD9C] rounded-2xl shadow-xl p-10">
    <div class="flex justify-center mt-6 mb-10">
      <p class="text-5xl max-lg:text-3xl max-md:text-xl font-bold text-[#514F4D] drop-shadow-md">
        MY ACADEMY QUEST
      </p>
    </div>
    <div class="flex justify-center mb-10">
      <%= image_tag "profile_img.jpeg", class: "w-60 h-60 object-cover rounded-full border-4 border-[#514F4D] shadow-lg"%>
    </div>
    <div class="flex justify-center mb-10">
      <p class="text-2xl max-lg:text-xl font-bold text-[#514F4D] drop-shadow-md">
        Nawamin Wongpakham (Dew)
      </p>
    </div>
    <div class="flex justify-center mb-10 max-md:flex-col max-md:items-center-safe">
      <%= link_to profile_path,data: { testid: "my-brag-doc-btn" }, class: "px-4 py-2 bg-[#3D4140] w-fit text-white rounded-lg hover:bg-[#353734] transition shadow-md" do %>
        <div class="flex justify-center">
          <p>My brag doccument</p>
        </div>
      <% end %>
      <div class="flex min-md:ml-10 max-md:mt-4">
        <%= link_to "https://github.com/Augustarr", target: "_blank", rel: "noopener", class: "flex items-center" do %>
          <%= image_tag "github-142-svgrepo-com.svg", class: "w-6 h-6 my-1"%>
        <% end %>
        <%= link_to "https://www.linkedin.com/in/nawamin-wongpakham-33492435b", target: "_blank", rel: "noopener", class: "flex items-center" do %>
          <%= image_tag "linkedin-rounded-svgrepo-com.svg", class: "w-6 h-6 my-1 ml-4"%>
        <% end %>
        <%= link_to "https://www.facebook.com/nawamin.wongpakham.2024", target: "_blank", rel: "noopener", class: "flex items-center" do %>
          <%= image_tag "facebook-svgrepo-com.svg", class: "w-7 h-7 ml-4"%>
        <% end %>
      </div>
    </div>
    <div class="flex justify-center mb-8">
      <turbo-frame id="new_todo" class="w-full max-w-2xl">
        <%= render "form", todo: Todo.new %>
      </turbo-frame>
    </div>
    <div class="flex justify-center">
      <div class="w-full max-w-2xl">
        <%= turbo_stream_from "todos" %>
        <ul id="todos-list" class="space-y-4">
          <%= render @todos %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>
<h1>New todo</h1>
<%= render "form", todo: @todo %>
<br>
<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>
<turbo-frame id="new_todo">
  <%= render @todo %>
  <turbo-frame>
    <div>
      <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
      <%= link_to "Back to todos", todos_path %>
      <%= button_to "Destroy this todo", @todo, method: :delete %>
    </div>